### ISSUE TITLE
Namespace template

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pydsdlgen#18]
Currently, pydsdlgen allows the user to map DSDL composite types to generated output files. I want to generate code for DSDL namespaces as well. For example, consider the following DSDL source tree:

* `uavcan` --> `uavcan/__init__.py` via `Namespace.j2`
  * `node`  --> `uavcan/node/__init__.py` via `Namespace.j2`
    * `32085.Heartbeat.1.0.uavcan` --> `uavcan/node/Heartbeat_1_0.py` via `StructureType.j2`
    * `430.GetInfo.1.0.uavcan` --> `uavcan/node/GetInfo_1_0.py` via `ServiceType.j2`

@thirtytwobits Does such use case seem to be in line with the objectives of this library? Would it be difficult to support it?

**Comment by thirtytwobits** [comment]
This would easy to do (It's Python: everything is easy to do).

**Comment by thirtytwobits** [comment]
So the requirements for this feature are a bit hard to generalize since this is a fairly Python-specific problem. I'm thinking we have the following:

1. API to provide pattern for which namespaces to generate a file for.
2. Optional name override for the generated namespace file.

For 2 what I'm thinking is that the default is simply:

```
{output_dir}/{namespace_name}.{output_extension}
```

but for python we allow this to be changed to:

```
{output_dir}/{parent_namespaces}/{namespace_name}/__init__.{output_extension}
```

Eh. This is a bit half-baked. It's late and I'm not thinking clearly. I'll post this comment anyway to see if you have suggestions. For example: what would this feature look like for C, C++, or some other non-python language?

**Comment by thirtytwobits** [comment]
Okay. I think I now how I'm going to do this now. PR will be up probably tomorrow.

**Comment by pavel-kirienko** [comment]
I was just about to start typing my comment here when I saw your last post. This is very cool because my pyuavcan adventures have reached the point where I need my namespaces packaged.

**Comment by thirtytwobits** [comment]
I posted a [prototype](https://github.com/thirtytwobits/pydsdlgen/commit/f967232164032b5768d787b0c3647727a816d5ee) but it's a bit of a hack since I'm synthesizing a new CompositeType: `Namespace`. It would be better if the pydsdl library did this (https://github.com/UAVCAN/pydsdl/issues/22) and pydsdlgen simply consumed it.

Thoughts?

**Comment by thirtytwobits** [comment]
Almost there. https://github.com/thirtytwobits/pydsdlgen/tree/feature/18 seems functional but I have one broken test to fix and I need to write more tests of the new namespace feature itself. This turned out to be slightly more work than I though it would be. Sorry.

**Comment by thirtytwobits** [comment]
Done.
